import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { getClient, getClientTrajectory, getClientWhatChanged, listClientActions, listClientAnalyses, listWorkspaceMembers, refreshClientLongitudinal, updateActionStatus } from '../services/api';
import type { ActionItem, Client, LongitudinalSignal, PersistedAnalysisResponse } from '../types';
import ClientWorkspacePage from './ClientWorkspacePage';

vi.mock('../services/api', () => ({ getClient: vi.fn(), getClientTrajectory: vi.fn(), getClientWhatChanged: vi.fn(), refreshClientLongitudinal: vi.fn(), listClientAnalyses: vi.fn(), listClientActions: vi.fn(), listWorkspaceMembers: vi.fn(), updateActionFollowUp: vi.fn(), updateActionStatus: vi.fn(), getAction: vi.fn(), ActionStatusConflictError: class extends Error {}, LongitudinalSignalConflictError: class extends Error {} }));
const mockedGet = vi.mocked(getClient); const mockedTrajectory = vi.mocked(getClientTrajectory); const mockedWhatChanged = vi.mocked(getClientWhatChanged); const mockedRefresh = vi.mocked(refreshClientLongitudinal); const mockedAnalyses = vi.mocked(listClientAnalyses); const mockedActions = vi.mocked(listClientActions); const mockedMembers = vi.mocked(listWorkspaceMembers); const mockedStatus = vi.mocked(updateActionStatus);
const client: Client = { id: 'client-1', display_name: 'Ada Client', external_reference: 'ADA-1', status: 'active', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-02T00:00:00Z' };
const finding = { finding_id: 'f1', category: 'sleep', title: 'Sleep', statement: 'Structured finding', classification: 'client_reported_information', confidence: 0.9, evidence: [], review_status: 'pending' as const };
const analysis: PersistedAnalysisResponse = { analysis_id: 'analysis-1', client_id: client.id, status: 'completed', created_at: '2026-01-03T00:00:00Z', client_reference: 'ADA-1', analysis_period: 'Week 1', weekly_summary: finding, findings: [finding], risk_flags: [], recommended_actions: [], missing_information: [], engine: 'deterministic', prompt_version: 'v1', validation_warnings: ['warning'], fallback_reason: null, review_status: 'approved', review_note: 'Reviewed safely', reviewed_at: '2026-01-04T00:00:00Z', review_version: 2 };
const action: ActionItem = { id: 'item-1', analysis_id: analysis.analysis_id, client_id: client.id, source_action_id: 'source-1', title: 'Client-specific follow-up', description: 'Stored rationale', priority: 1, status: 'in_progress', linked_finding_ids: [], due_at: null, completed_at: null, assignee_membership_id: null, completion_outcome: null, assignee: null, created_at: '2026-01-03T00:00:00Z', updated_at: '2026-01-04T00:00:00Z', version: 2 };
const signal: LongitudinalSignal = { id: 'signal-1', client_id: client.id, canonical_key: 'sleep', signal_kind: 'theme', temporal_state: 'active', trend_direction: 'stable', summary: 'Draft sleep theme', explanation: 'Evidence-backed explanation', trust_state: 'draft', first_observed_at: '2026-01-01T00:00:00Z', last_observed_at: '2026-01-02T00:00:00Z', observation_count: 1, version: 1, reviewed_at: null, evidence: [{ action_item_id: action.id, action_field: 'status', evidence_role: 'supports' }] };
function renderPage() { return render(<MemoryRouter initialEntries={['/clients/client-1']}><Routes><Route path="/clients/:clientId" element={<ClientWorkspacePage />} /></Routes></MemoryRouter>); }
beforeEach(() => { vi.clearAllMocks(); mockedGet.mockResolvedValue(client); mockedTrajectory.mockResolvedValue({ client_id: client.id, trusted_signals: [], review_required: [signal], action_item_aggregates: { open_count: 0, completed_count: 0 }, deterministic_metrics: {} }); mockedWhatChanged.mockResolvedValue({ client_id: client.id, comparison_analysis_id: null, items: [{ signal_id: null, change_kind: 'insufficient_history', summary: 'Insufficient approved history.', evidence: [] }] }); mockedRefresh.mockResolvedValue({ processed_analysis_count: 0, processed_action_item_count: 0, created_draft_signal_count: 0, updated_draft_signal_count: 0, invalidated_trusted_signal_count: 0, semantic_status: 'not_needed' }); mockedAnalyses.mockResolvedValue({ items: [analysis], offset: 0, limit: 100, returned_count: 1 }); mockedActions.mockResolvedValue({ items: [], offset: 0, limit: 100, returned_count: 0 }); mockedMembers.mockResolvedValue({ items: [{ membership_id: 'member-2', display_name: 'Grace Hopper', email: 'grace@example.test', role: 'member' }] }); });

describe('ClientWorkspacePage', () => {
  it('shows loading while real data is pending', () => { mockedGet.mockReturnValue(new Promise(() => {})); mockedAnalyses.mockReturnValue(new Promise(() => {})); renderPage(); expect(screen.getByText(/Loading client workspace/)).toBeInTheDocument(); });
  it('renders client metadata and real analysis history with saved links', async () => { renderPage(); expect(await screen.findByText('Ada Client')).toBeInTheDocument(); expect(screen.getByText('ADA-1')).toBeInTheDocument(); expect(screen.getByText('Week 1')).toBeInTheDocument(); expect(screen.getByText('Reviewed safely')).toBeInTheDocument(); expect(screen.getByRole('link', { name: 'Open saved analysis' })).toHaveAttribute('href', '/analyses/analysis-1'); expect(screen.queryByText(/Coach|attention|Evidence trace/i)).not.toBeInTheDocument(); });
  it('shows a zero-analysis state', async () => { mockedAnalyses.mockResolvedValue({ items: [], offset: 0, limit: 100, returned_count: 0 }); renderPage(); expect(await screen.findByText('No linked analyses')).toBeInTheDocument(); });
  it('shows a missing client state', async () => { mockedGet.mockRejectedValue(new Error('The requested client was not found.')); renderPage(); expect(await screen.findByText('Client not found')).toBeInTheDocument(); });
  it('shows generic errors and retries', async () => { mockedGet.mockRejectedValueOnce(new Error('Safe failure')).mockResolvedValueOnce(client); renderPage(); const user = userEvent.setup(); await user.click(await screen.findByRole('button', { name: 'Retry' })); expect(await screen.findByText('Ada Client')).toBeInTheDocument(); });
  it('never renders original conversation or raw analysis output', async () => { renderPage(); await screen.findByText('Ada Client'); expect(document.body).not.toHaveTextContent('original conversation'); expect(document.body).not.toHaveTextContent('analysis_output'); });
  it('renders only real Client-scoped Action Items', async () => { mockedActions.mockResolvedValue({ items: [action], offset: 0, limit: 100, returned_count: 1 }); renderPage(); expect(await screen.findByText('Client-specific follow-up')).toBeInTheDocument(); expect(screen.getByText(/Priority 1/)).toBeInTheDocument(); expect(mockedActions).toHaveBeenCalledWith('client-1'); });
  it('reuses the shared human-controlled follow-up editor', async () => { mockedActions.mockResolvedValue({ items: [action], offset: 0, limit: 100, returned_count: 1 }); const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole('button', { name: 'Edit follow-up' })); expect(screen.getByLabelText('Assignee')).toHaveValue(''); expect(screen.getByRole('option', { name: 'Grace Hopper' })).toBeInTheDocument(); expect(mockedMembers).toHaveBeenCalledTimes(1); });
  it('synchronizes status and outcome controls when the shared card receives an authoritative completion response', async () => { mockedActions.mockResolvedValue({ items: [action], offset: 0, limit: 100, returned_count: 1 }); const completed = { ...action, status: 'completed' as const, completion_outcome: 'Server-confirmed outcome', completed_at: '2026-09-05T05:00:00Z', version: 3 }; mockedStatus.mockResolvedValue(completed); const user = userEvent.setup(); renderPage(); await user.selectOptions(await screen.findByLabelText('Status'), 'completed'); await user.type(screen.getByLabelText(/Completion outcome/), 'Human draft outcome'); await user.click(screen.getByRole('button', { name: 'Complete Action' })); await screen.findByText('Outcome', { selector: 'dt' }); expect(screen.getByLabelText('Status')).toHaveValue('completed'); expect(screen.getByLabelText(/Completion outcome/)).toHaveValue('Server-confirmed outcome'); });
  it('shows insufficient history, review-required work, and never places drafts in trusted trajectory', async () => { renderPage(); expect(await screen.findByText(/Insufficient approved history/)).toBeInTheDocument(); expect(screen.getByText('Review required')).toBeInTheDocument(); expect(screen.getByText('Draft sleep theme')).toBeInTheDocument(); expect(screen.queryByText('Trusted trajectory: Draft sleep theme')).not.toBeInTheDocument(); });
  it('shows refresh loading and a safe refresh error', async () => { mockedRefresh.mockRejectedValue(new Error('private provider detail')); const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole('button', { name: 'Refresh longitudinal intelligence' })); expect(await screen.findByRole('alert')).toHaveTextContent(/could not be refreshed/i); expect(screen.queryByText('private provider detail')).not.toBeInTheDocument(); });
  it('provides labeled refresh and review controls', async () => { renderPage(); expect(await screen.findByRole('button', { name: 'Refresh longitudinal intelligence' })).toBeInTheDocument(); expect(screen.getByLabelText('Intelligence review')).toBeInTheDocument(); });
});
